services:
  dash-frontend:
    build: ./frontend_new
    ports:
      - "5555:5555" # Host:Container
    depends_on:
      - dash-backend
    networks:
      - app-network

  dash-backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
