name: Deploy to homelab

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_USER }}"
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Pull and rebuild containers
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git fetch && git pull && \
                                                                cd ${{ secrets.COMPOSE_DIR }} && \
                                                                docker compose -f run-services.yml up -d --build dash-backend && \
                                                                docker compose -f run-services.yml up -d --build dash-frontend"

      - name: Cleanup
        run: rm -rf ~/.ssh/
